spring.application.name=demo
server.port=8080

jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySl
jwt.expiration=3600000
spring.datasource.url=jdbc:h2:mem:demodb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=12345678
cashfree.client-id=TEST11233369f82f27138115f828b26b96333211
cashfree.client-secret=cfsk_ma_test_fc2cfa535c1a56a9dcee0f01332963f8_cf908225
cashfree.base-url=https://sandbox.cashfree.com/pg
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console